### ISSUE TITLE
Permitir sobreposição dos detectores, porem mantendo o centro fora da área de outro detector, utilizando distancia euclideana.

### ISSUE THREAD

**Issue by TsunekiR** [hpc-fci-mackenzie/FlakyBuild#5]
Permitir que tenha intersecção entre as áreas de detectores diferentes, porem não permitir que seja gerado um detector com centro na área de detecção de outro detector.
Valido:
![image](https://user-images.githubusercontent.com/53917975/89548153-0b90ba80-d7dd-11ea-803d-1a33a3a3840b.png)

Nao-valido:
![image](https://user-images.githubusercontent.com/53917975/89548306-3aa72c00-d7dd-11ea-9d83-bbcceefb68bc.png)

**Comment by TsunekiR** [comment]
imagens temporarias

**Comment by rodrigopp22** [comment]
Issue transferred to Issue#28
