### ISSUE TITLE
Criação de um novo parâmetro para finalizar a geração de detectores.

### ISSUE THREAD

**Issue by TsunekiR** [hpc-fci-mackenzie/FlakyBuild#6]
Criação de um limite de detectores inválidos gerados baseado no percentual de cobertura alvo da área nonself. Dado pela equação:

![image](https://user-images.githubusercontent.com/53917975/89548761-cde06180-d7dd-11ea-9c0c-73c1d6bd62a1.png)
Onde A é o percentual de cobertura alvo da área nonself e L o limite.

**Comment by rodrigopp22** [comment]
This issue will be transferred to Issue#26
